### ISSUE TITLE
CACHE_DB_CONNECTION sql migration

### ISSUE THREAD

**Issue by Tarnadas** [NEAR-Edu/stats.gallery-server#4]
Hey,

I was trying to set up the server locally and it seems like the README is missing information about how to set up the cache db.
I started a local instance of postgres and set up the CACHE_DB_CONNECTION environment variable, but idk about the migration that I need to run for the account table, which is why I get this error:

```
❯ npm run start

> server@0.1.0 start /home/marior/projects/shroom-kingdom/stats.gallery-server
> node -r dotenv/config ./index.js

Listening on port 3000...
cachePoolConnectionString postgres://stats:password@172.17.0.3
Connection postgres://public_readonly:nearprotocol@104.199.89.51/mainnet_explorer
updating cache
Loading accounts...
Waiting for requests...
(node:388589) UnhandledPromiseRejectionWarning: error: relation "account" does not exist
    at Parser.parseErrorMessage (/home/marior/projects/shroom-kingdom/stats.gallery-server/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/home/marior/projects/shroom-kingdom/stats.gallery-server/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/home/marior/projects/shroom-kingdom/stats.gallery-server/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/home/marior/projects/shroom-kingdom/stats.gallery-server/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (events.js:375:28)
    at Socket.emit (domain.js:470:12)
    at addChunk (internal/streams/readable.js:290:12)
    at readableAddChunk (internal/streams/readable.js:265:9)
    at Socket.Readable.push (internal/streams/readable.js:204:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
```

**Comment by encody** [comment]
Thanks for the report. I've added migrations & a README section for setting up the cache database. Please let me know if you encounter any problems with them.

**Comment by Tarnadas** [comment]
Thx for helping out. I'll prepare a PR which fixed a couple of initialization problems, if you don't use a database dump
